version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dev_gopos
    volumes:
      - .:/workspace:cached
      - ~/.gitconfig:/home/vscode/.gitconfig
      - ~/.ssh:/home/vscode/.ssh
      - ~/.zsh_history:/home/vscode/.zsh_history
    command: "sleep infinity"

  postgres:
    image: postgres:16.1-alpine3.19
    container_name: postgres_gopos
    ports:
      - 5432:5432
    volumes:
      - gopos-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d gopos" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.3-alpine
    container_name: redis_gopos
    ports:
      - 6379:6379
    volumes:
      - gopos-redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 5s
      retries: 5

volumes:
  gopos-postgres:
    driver: local
  gopos-redis:
    driver: local
