name: Continuous Integration

on:
  push:
    branches: ["main", "stable"]
  pull_request:
    branches: ["main", "stable"]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: false

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: "v1.55"
          config: .golangci.yml

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./... -race -cover -timeout 10s
